### ISSUE TITLE
Help with Subsettings

### ISSUE THREAD

**Issue by TheXRMonk** [hextantstudios/com.hextantstudios.utilities#3]
I can't get them to show up. Normal settings work fine. 
It would be a good idea with an example in the documentation :)

**Comment by Hextant** [comment]
Sorry, I do not understand what you're trying to do. There's an example on the [website article](https://hextantstudios.com/unity-custom-settings/) if you haven't already seen that.

**Comment by TheXRMonk** [comment]
> Sorry, I do not understand what you're trying to do. There's an example on the [website article](https://hextantstudios.com/unity-custom-settings/) if you haven't already seen that.

Yes, I've seen that. In there it mentiones "subsettings". 
I am guessing that make the settings render like subsettings under (for instance) _services_ in the attached image;
![image](https://user-images.githubusercontent.com/54309738/131371931-90d56d81-7480-42aa-9821-889d4c6a29e4.png)
But I'm guessing that's not the case?

**Comment by Hextant** [comment]
You can use a path-style name using the `/` separator in the settings' name to get nested/parented settings to appear in the settings dialogs. For example: instead of "My Plug-in Settings" you can do "Services/My Plug-in Settings" to have them appear under "Services". I'll update the article to mention that as it's only mentioned in the [SettingsProvider.settingsPath](https://docs.unity3d.com/ScriptReference/SettingsProvider.html) documentation right now.

The `SubSettings` class just allows you to break up a _single_ `Settings` class into multiple C# classes if you have a lot of settings, but you still want it to appear as a single entry in the settings dialog. It provides a `Set<T>()` method that properly handles checking for a change and marks the "owning" `Settings` instance as dirty so that it will be saved. I'll try to add an example for that to the article as well. If you were to just use a regular C# class, you would have to manage dirtying the `Settings` instance yourself.

**Comment by Hextant** [comment]
Ok, I updated the [article](https://hextantstudios.com/unity-custom-settings/) with directions on how to nest settings as mentioned above and also an example of how to use the `SubSettings` class. Let me know if you have any other questions.

**Comment by TheXRMonk** [comment]
Makes sense! Thanks!
